export {default as Navbar} from './Navbar/Navbar';
export {default as Footer} from './Footer/Footer';
export {default as Products} from './Products/Products';
export {default as Fav} from './Fav/Fav';
export {default as ProductSite} from './Products/ProductSite/ProductSite';
export {default as Slideshow} from './Slideshow/Slideshow';
export {default as PersonalPage} from './PersonalPage/PersonalPage';
export {default as Category} from './Category/Category';
export {default as SignInForm} from './SignInForm/SignInForm';
export {default as SignUpForm} from './SignUpForm/SignUpForm';
export{default as AddProduct} from './AddProduct/AddProduct';
export{default as ChangeProduct} from './ChangeProduct/ChangeProduct';
export{default as ListProduct} from './ListProduct/ListProduct'; 
export {default as CheckoutInfo} from './CheckoutForm/CheckoutInfo/CheckoutInfo';
export {default as CheckoutMethod} from './CheckoutForm/CheckoutMethod/CheckoutMethod';
export {default as CheckoutSuccess} from './CheckoutForm/CheckoutSuccess/CheckoutSuccess';
export {default as EditProfile} from './Edit/EditProfile/EditProfile';
export {default as StorePage} from './PersonalPage/StorePage';
export {default as News} from './News/News';
export {default as Popup} from './Popup/Popup';
export {default as PagesBtn} from './AllPageButton/PagesBtn';